In [1]:
import pandas as pd

In [2]:
# 지역화폐가맹점 Dataframe
local_m = pd.read_csv('datas/지역화폐가맹점(20230228기준).csv', index_col = 0, encoding='CP949', low_memory=False)
local_m

,상호명,업종명(종목명),소재지도로명주소,소재지지번주소,우편번호,위도,경도,데이터기준일자,사업자등록번호,업종코드,가맹점번호,휴폐업 정보,휴폐업상태코드,폐업일자
시군명,,,,,,,,,,,,,,
고양시,별미냉면(신원점),일반한식,경기도 고양시 덕양구 신원로 10,경기도 고양시 덕양구 신원동 633번지 1층 101호 102호,10571.0,37.661855,126.890313,2023-02-28,2527300435,8001,726174525,계속사업자,1.0,NaN
고양시,맘스터치,서양음식,경기도 고양시 덕양구 충장로 134,경기도 고양시 덕양구 행신동 943-1번지 아이프라자 114호,10495.0,37.624376,126.834956,2023-02-28,6021318801,8006,794574007,계속사업자,1.0,NaN
고양시,경희원도태권스쿨,예체능계학원,경기도 고양시 일산동구 강송로 115,경기도 고양시 일산동구 백석동 1225번지 중앙프라자상가 405호,10420.0,37.649266,126.786375,2023-02-28,1289195220,5104,752194347,폐업자,3.0,2023-01-30
고양시,이내과의원,의원,경기도 고양시 일산동구 숲속마을1로 73,경기도 고양시 일산동구 풍동 1274-1번지 신성메디칼 2층 201호,10306.0,37.667635,126.799851,2023-02-28,1289233895,7020,761054505,계속사업자,1.0,NaN
고양시,전의명가,일반한식,경기도 고양시 일산서구 일중로15번길 82,경기도 고양시 일산서구 일산동 655-395번지 1층 일부호,10353.0,37.682860,126.770460,2023-02-28,1410420872,8001,773177770,계속사업자,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
김포시,더쉐프팩토리,일반한식,경기도 김포시 양촌읍 김포한강4로 341-12,경기도 김포시 양촌읍 석모리 951-34번지,10065.0,37.650315,126.645822,2023-02-28,2992500622,8001,710738739,계속사업자,1.0,NaN
김포시,빈센트 미술교습소,예체능계학원,경기도 김포시 사우중로74번길 29,경기도 김포시 사우동 880번지 시그마프라자 6층 601-2호,10111.0,37.621699,126.721550,2023-02-28,2239307442,5104,711402597,계속사업자,1.0,NaN
김포시,빌리어드 당구클럽,당구장,NaN,경기도 김포시 감정동 550-1번지 신한아파트 2층,10105.0,37.622916,126.700007,2023-02-28,6591901332,2121,720009381,계속사업자,1.0,NaN
성남시,북경성반점,음식점업,경기도 성남시 수정구 복정로 92,경기도 성남시 수정구 복정동 678-3번지 102호 북경성반점,13112.0,37.461073,127.127008,2023-02-28,1293612112,2,MRC00000000000069140,폐업자,3.0,2020-10-16
성남시,섬마을고깃간,소매업,경기도 성남시 중원구 도촌남로 33,경기도 성남시 중원구 도촌동 567번지 세일프라자 103호 섬마을고깃간,13426.0,37.414564,127.151139,2023-02-28,1459500838,0,MRC00000000000020258,폐업자,3.0,2021-12-22

In [3]:
current_store = local_m[local_m['휴폐업 정보'] == '계속사업자']

In [4]:
current_store['업종명(종목명)'].unique()

array(['일반한식', '서양음식', '의원', '스넥', '기계공구', '기타잡화', '헬스클럽', '피부미용실', '제과점',
       '슈퍼마켓', '약국', '자동차부품', '치과의원', '용역서비스', '중국식', '편의점', '화원', '한의원',
       '농,축협직영매장', '보습학원', '기타교육기관', '기타용역서비스', '기타레져업소', '기타유통업', '화장품',
       '예체능계학원', '주점', '미용원', '외국어학원', '관광여행', '사진관', '기타건축자재', '기타음료식품',
       '내의판매', '기타대인서비스', '농축수산품', '일반가구', '안경', '주방용식기', '완구점', '주방용구',
       '목재석재철물', '문화취미기타', '사무통신기기수리', '자동차정비', '애완동물', '동물병원', '홍삼제품',
       '기능학원', '정육점', '당구장', '의료용품', '수영장', '렌터카', '인테리어전문', '세탁소',
       '카페트,커튼,천막,지물', '일식회집', '정장', '스포츠의류', '학원', '스포츠레져용품', '세차장',
       '기타가구', '액세서리', '기타운송', '페인트', '미용재료', '기타3', '이륜차판매', '악기점', '신발',
       '독서실', '기타건강식품', '기타전문점', '통신기기', '카인테리어', '기타사무용품', '건축용요업제품',
       '일반서적', '비영리/대상', '여관/기타숙박업', '문구용품', '침구수예점', '주류판매점', '사우나',
       '보관및창고업', '소프트웨어', '기타4', '위탁급식업', '아동의류', '노래방', '가정용품수리', '귀금속',
       '테니스장', '칵테일바', '기타의료기관및기타의료기기', '유류판매', '스크린골프', '기타의류', '이용원',
       '레져업소', '부동산중개임대', '출판및인쇄물', '법률회계서비스(개인)', '맞춤복점', '농기계', '조명기구',
       '골프연습장', '시계', '컴퓨터학원', '보일러펌프샷시', '통신기기(무이자할부)', '화물운송', '주차장',
       '민예공예품', '종합용역', '중고자동차판매', '제화', '기념품점', '컴퓨터', '가전제품', '서적',
       '단체복', '유리', '가방', '치과병원', '산후조리원', '인삼제품', '안마시술소', '유아원',
       '자동차시트타이어', '비료,사료,종자', '볼링장', '옷감직물', '윤활유전문판매', '와이셔츠타이', '미곡상',
       'SK가스충전소', '현대정유(오일뱅크)', '골프용품전문점', '기타수리서비스', '기타전기제품', '티켓',
       'SK주유소', '사무용OA기기', '기타농업관련', '정보서비스', '병원', 'LPG취급점', '기타1',
       '가타자동차서비스', '혼수전문점', '기타서적문구', '쌍용S-OIL', 'GS주유소', '가례서비스업',
       '레져용품수리', '화방표구점', '전문서적', '영화관', '인터넷Mall', '주유소', '상품권', '수족관',
       '화랑', '과학기자재', '냉열기기', '기타광학제품', '카메라', '혼례서비스', '음반/영상물', '건강식품',
       '통신판매업2', '기타연료', 'E1가스충전소', '법률회계서비스(법인)', '콘도', '쌍용S-OIL가스충전소',
       '신변잡화수리', '견인서비스', '조세서비스', '구내매점(국가기관등)', '중장비수리', '정수기', '학습지교육',
       '철제가구', '한약방', '정기간행물', '유학원', '회원제형태업소', '피아노대리점', '기타주방용구',
       '복지매장', '기타직물', '자체물품대금', '종합병원', '자동차서비스', '2급호텔', '상품권전문판매',
       '기타교통수단', '정장(여성)', '골동품점', '부동산분양', 'GS가스충전소', '유치원', '기타보험',
       '제약회사', '한정식', '농축수산가공품', '수입자동차', '국산신차직영부품정비업소', '기타2',
       '비영리/비대상', '한방병원', '갈비전문점', '양품점', '연쇄점', '전자(상우회)', '캐주얼의류',
       '소매업', '대형할인점', '조산원', '교육서비스업', '고속버스', '택시', '현대정유가스충전소',
       '조세서비스(특약)', '골프경기장', '여객선', '음식점업', '스포츠및여가관련서비스업', '개인서비스업',
       '보건업', '제조업', '기타', '숙박업', '여성청소년생필품', '성인용품점', '일반(통신판매)', '유흥주점',
       '농협하나로클럽', '일반자판기', '교육용테이프판매', '종합레져타운', 'CATV', '국산신차판매'],
      dtype=object)

In [5]:
local_market = pd.read_csv('datas/전통시장현황(개방표준).csv', encoding='CP949', low_memory=False)
local_market

,시장명,시장유형,소재지도로명주소,소재지지번주소,시장개설주기,위도,경도,점포수,취급품목,사용가능상품권,홈페이지주소,공중화장실보유여부,주차장보유여부,개설연도,전화번호,데이터기준일자
0,청평여울시장,상설장,경기도 가평군 청평면 청평중앙로26번길 10,경기도 가평군 청평면 청평리 424-7번지,매일,37.736015,127.418135,104,"농산물,의류,잡화",온누리상품권+가평사랑상품권,NaN,Y,N,2018.0,031-584-0000,2022-06-14
1,가평잣고을전통시장,상설장,경기도 가평군 가평읍 가화로 116-1,경기도 가평군 가평읍 읍내리 473-15번지,매일,37.839986,127.520386,137,"농산물,의류,잡화",온누리상품권+가평사랑상품권,NaN,Y,N,2015.0,031-582-8181,2022-06-14
2,패션1번지,상설장,경기도 고양시 일산서구 탄중로101번길 13,경기도 고양시 일산서구 덕이동 384-1번지,매일,37.693019,126.755789,59,패션의류,온누리상품권,NaN,Y,Y,2007.0,031-917-6669,2021-12-02
3,일산시장,상설장,경기도 고양시 일산서구 일청로12번길 9,경기도 고양시 일산서구 일산동 617-20번지,매일,37.685622,126.770828,88,농수축산물+잡화,온누리상품권,NaN,Y,Y,1979.0,031-975-2232,2021-12-02
4,능곡시장,상설장,경기도 고양시 덕양구 능곡로 12-9,경기도 고양시 덕양구 토당동 348-9번지,매일,37.621271,126.821151,78,농수축산물+잡화,온누리상품권,NaN,Y,N,2011.0,031-973-3727,2021-12-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,덕풍시장,상설장+5일장,경기도 하남시 신장로154번길 57,경기도 하남시 덕풍동 326-9번지,"매일,+4일,+ 9일",37.541814,127.203516,148,"농.축산물.의류.분식,잡화 등",온누리상품권,NaN,Y,Y,2005.0,031-794-3753,2019-03-27
152,조암시장,5일장,경기도 화성시 우정읍 조암남로 28,경기도 화성시 우정읍 조암리 270-7번지 일원,"4,9일장",37.083174,126.818206,400,"농산물,생필품",온누리상품권,NaN,NaN,Y,1929.0,031-351-8009,2022-06-15
153,사강시장,5일장,경기도 화성시 송산면 송산포도로 109-2,경기도 화성시 송산면 사강리 631-21번지 일원,"2,7일장",37.216227,126.739863,347,"농산물,생필품",온누리상품권,NaN,NaN,Y,1924.0,031-357-6037,2022-06-15
154,발안만세시장,5일장,경기도 화성시 향남읍 3.1만세로 1131,경기도 화성시 향남읍 평리 30-8번지 일원,"5,10일장",37.131481,126.909568,214,"농산물,생필품",온누리상품권,www.bamk.co.kr,Y,Y,1929.0,031-352-0120,2022-06-15
155,남양시장,5일장,경기도 화성시 남양읍 남양시장로 61,경기도 화성시 남양읍 남양리 1165-25번지 일원,"1,6일장",37.208885,126.815359,434,"농산물,생필품",온누리상품권,NaN,Y,Y,1935.0,031-366-9100,2022-06-15

In [6]:
place='수원시', '성남시', '고양시', '부천시', '용인시', '안산시', '안양시', '남양주시', '의정부시', '평택시', '시흥시', '화성시', '광명시', '파주시', '군포시', '광주시', '김포시', '이천시', '구리시', '양주시', '안성시', '포천시', '오산시', '하남시', '의왕시', '동두천시', '과천시', '여주군', '양평군', '가평군', '연천군'

## 각 시/군에 있는 전통시장의 개수 구하기

In [7]:
place='수원시', '성남시', '고양시', '부천시', '용인시', '안산시', '안양시', '남양주시', '의정부시', '평택시', '시흥시', '화성시', '광명시', '파주시', '군포시', '광주시', '김포시', '이천시', '구리시', '양주시', '안성시', '포천시', '오산시', '하남시', '의왕시', '동두천시', '과천시', '여주군', '양평군', '가평군', '연천군'
count_market_list = []
for i in place:
    count_market = local_market['소재지도로명주소'].str.contains(i).sum()
    count_market_list.append(count_market)
count_market_list

[22,
 30,
 4,
 18,
 2,
 1,
 5,
 3,
 3,
 5,
 4,
 4,
 2,
 7,
 2,
 1,
 4,
 3,
 1,
 3,
 4,
 10,
 1,
 2,
 1,
 4,
 2,
 0,
 4,
 2,
 1]

## 경기도 시/군 31개가 모두 잘 카운트 되었는지 확인하기

In [8]:
place='수원시', '성남시', '고양시', '부천시', '용인시', '안산시', '안양시', '남양주시', '의정부시', '평택시', '시흥시', '화성시', '광명시', '파주시', '군포시', '광주시', '김포시', '이천시', '구리시', '양주시', '안성시', '포천시', '오산시', '하남시', '의왕시', '동두천시', '과천시', '여주군', '양평군', '가평군', '연천군'
count_stores_in_market_list = []
for i in place:
    count_stores = local_market.loc[local_market['소재지도로명주소'].str.contains(i), '점포수'].sum()
    count_stores_in_market_list.append(count_stores)
len(count_stores_in_market_list)

31

In [35]:
market_table = {'place': place, 'count_market': count_market_list, 'count_stores': count_stores_in_market_list, 'local_money':''
}

In [36]:
# 경기지역화폐 지류형 사용 지역
# 안산시, 시흥시, 의왕시, 안양시, 성남시, 과천시, 포천시, 평택시,

In [ ]:
titanic['alive']=titanic.apply(lambda x: True if x.alive=='yes' else False, axis=1)

In [52]:
%pwd

'C:\\python'

## 경기도 내 31개의 시/군에 있는 시장 총 개수와 점포의 총 개수

In [55]:
# 경기도 내 31개의 시/군에 있는 시장 총 개수와 점포의 총 개수 
df = pd.DataFrame(market_table)
local_market_insight=df.sort_values(['count_market','count_stores'], ascending=False)
local_market_insight['local_money']=local_market_insight.apply(lambda x: True if x.place=='안산시'or x.place=='시흥시'or x.place=='의왕시'or x.place=='안양시'or x.place=='성남시'or x.place=='과천시'or x.place=='포천시'or x.place=='평택시' else False, axis=1)
local_market_insight.reset_index(inplace=True, drop=True)
local_market_insight

   place  count_market  count_stores  local_money
0    성남시            30          3848         True
1    수원시            22          3240        False
2    부천시            18          1787        False
3    포천시            10           603         True
4    파주시             7           818        False
5    평택시             5          1283         True
6    안양시             5          1027         True
7    양평군             4          1634        False
8    화성시             4          1395        False
9    안성시             4           388        False
10   김포시             4           354        False
11   시흥시             4           320         True
12  동두천시             4           309        False
13   고양시             4           284        False
14  의정부시             3           762        False
15  남양주시             3           336        False
16   양주시             3           336        False
17   이천시             3           238        False
18   용인시             2           620        False
19   광명시             2           592        False
20   과천시             2           261         True
21   군포시             2           260        False
22   가평군             2           241        False
23   하남시             2           224        False
24   안산시             1           410         True
25   구리시             1           388        False
26   오산시             1           350        False
27   의왕시             1           113         True
28   광주시             1            80        False
29   연천군             1            65        False
30   여주군             0             0        False

In [57]:
local_market_insight.to_csv("local_market_insights.csv", index = False)

In [40]:
publish_df = pd.read_csv('datas/지역화폐발행및이용현황.csv', encoding='CP949', low_memory=False)
publish_df.sort_values(['시군명','기준년월'], ascending=True)

,시군명,기준년월,월별카드발행수량(건),월별카드충전액(천원),월별카드사용액(천원),월별모바일상품권이용등록자수(명),월별모바일충전액(천원),월별모바일사용액(천원),월별지류상품권판매액(천원),월별지류상품권회수액(천원)
47,가평군,2019-01,NaN,NaN,NaN,NaN,NaN,NaN,153685.0,114460.0
46,가평군,2019-02,NaN,NaN,NaN,NaN,NaN,NaN,95445.0,129565.0
45,가평군,2019-03,1.0,NaN,NaN,NaN,NaN,NaN,120915.0,129565.0
44,가평군,2019-04,87.0,8870.0,2187.0,NaN,NaN,NaN,64575.0,93815.0
43,가평군,2019-05,506.0,109979.0,59447.0,NaN,NaN,NaN,73435.0,96675.0
...,...,...,...,...,...,...,...,...,...,...
1444,화성시,2022-08,5261.0,24110738.0,28903270.0,NaN,NaN,NaN,NaN,NaN
1443,화성시,2022-09,5000.0,44803542.0,35060747.0,NaN,NaN,NaN,NaN,NaN
1442,화성시,2022-10,6447.0,40644628.0,36969273.0,NaN,NaN,NaN,NaN,NaN
1441,화성시,2022-11,6159.0,38054887.0,35992147.0,NaN,NaN,NaN,NaN,NaN
1440,화성시,2022-12,5952.0,44546249.0,37550453.0,NaN,NaN,NaN,NaN,NaN

In [34]:
publish_df[publish_df['시군명']=='하남시'].sort_values('기준년월', ascending=True)

,시군명,기준년월,월별카드발행수량(건),월별카드충전액(천원),월별카드사용액(천원),월별모바일상품권이용등록자수(명),월별모바일충전액(천원),월별모바일사용액(천원),월별지류상품권판매액(천원),월별지류상품권회수액(천원)
1439,하남시,2019-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1438,하남시,2019-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1437,하남시,2019-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1436,하남시,2019-04,68.0,13630.0,1788.0,NaN,NaN,NaN,NaN,NaN
1435,하남시,2019-05,4291.0,2415632.0,430476.0,NaN,NaN,NaN,NaN,NaN
1434,하남시,2019-06,3254.0,1759139.0,1478470.0,NaN,NaN,NaN,NaN,NaN
1433,하남시,2019-07,2085.0,1621539.0,1872651.0,NaN,NaN,NaN,NaN,NaN
1432,하남시,2019-08,1036.0,924288.0,1503751.0,NaN,NaN,NaN,NaN,NaN
1431,하남시,2019-09,3161.0,2798078.0,2010501.0,NaN,NaN,NaN,NaN,NaN
1430,하남시,2019-10,3334.0,3819018.0,2596121.0,NaN,NaN,NaN,NaN,NaN
1429,하남시,2019-11,1208.0,1338598.0,2414000.0,NaN,NaN,NaN,NaN,NaN
1428,하남시,2019-12,1186.0,1969308.0,2230556.0,NaN,NaN,NaN,NaN,NaN
1427,하남시,2020-01,3054.0,3964313.0,3047035.0,NaN,NaN,NaN,NaN,NaN
1426,하남시,2020-02,3240.0,4428066.0,3175335.0,NaN,NaN,NaN,NaN,NaN
1425,하남시,2020-03,7450.0,8309745.0,4702156.0,NaN,NaN,NaN,NaN,NaN
1424,하남시,2020-04,36195.0,6654288.0,5686143.0,NaN,NaN,NaN,NaN,NaN
1423,하남시,2020-05,13447.0,7519662.0,6550214.0,NaN,NaN,NaN,NaN,NaN
1422,하남시,2020-06,5434.0,12286334.0,8112187.0,NaN,NaN,NaN,NaN,NaN
1421,하남시,2020-07,5426.0,11668179.0,10907893.0,NaN,NaN,NaN,NaN,NaN
1420,하남시,2020-08,2815.0,7072406.0,10085827.0,NaN,NaN,NaN,NaN,NaN
1419,하남시,2020-09,6101.0,13978351.0,12461378.0,NaN,NaN,NaN,NaN,NaN
1418,하남시,2020-10,3736.0,7841706.0,11015434.0,NaN,NaN,NaN,NaN,NaN
1417,하남시,2020-11,3461.0,8547934.0,9778813.0,NaN,NaN,NaN,NaN,NaN
1416,하남시,2020-12,3899.0,7453124.0,8355784.0,NaN,NaN,NaN,NaN,NaN
1415,하남시,2021-01,5036.0,16786656.0,12087623.0,NaN,NaN,NaN,NaN,NaN
1414,하남시,2021-02,8152.0,14783500.0,10857874.0,NaN,NaN,NaN,NaN,NaN
1413,하남시,2021-03,5811.0,14783500.0,10857874.0,NaN,NaN,NaN,NaN,NaN
1412,하남시,2021-04,5439.0,14045307.0,14721749.0,NaN,NaN,NaN,NaN,NaN
1411,하남시,2021-05,4153.0,11646402.0,13880948.0,NaN,NaN,NaN,NaN,NaN
1410,하남시,2021-06,12799.0,12333237.0,13706501.0,NaN,NaN,NaN,NaN,NaN
1409,하남시,2021-07,4135.0,10090753.0,11165096.0,NaN,NaN,NaN,NaN,NaN
1408,하남시,2021-08,3915.0,10090753.0,11165096.0,NaN,NaN,NaN,NaN,NaN
1407,하남시,2021-09,8006.0,10090753.0,11165096.0,NaN,NaN,NaN,NaN,NaN
1406,하남시,2021-10,7507.0,13164005.0,14264915.0,NaN,NaN,NaN,NaN,NaN
1405,하남시,2021-11,7218.0,23558168.0,19040971.0,NaN,NaN,NaN,NaN,NaN
1404,하남시,2021-12,4363.0,15399628.0,20204296.0,NaN,NaN,NaN,NaN,NaN
1403,하남시,2022-01,4172.0,18781248.0,20083773.0,NaN,NaN,NaN,NaN,NaN
1402,하남시,2022-02,4045.0,21998381.0,19230644.0,NaN,NaN,NaN,NaN,NaN
1401,하남시,2022-03,3534.0,11195207.0,17341245.0,NaN,NaN,NaN,NaN,NaN
1400,하남시,2022-04,4312.0,22600737.0,21020908.0,NaN,NaN,NaN,NaN,NaN
1399,하남시,2022-05,3730.0,27086752.0,24481135.0,NaN,NaN,NaN,NaN,NaN
1398,하남시,2022-06,3611.0,16283405.0,19528480.0,NaN,NaN,NaN,NaN,NaN
1397,하남시,2022-07,5450.0,6725929.0,11347566.0,NaN,NaN,NaN,NaN,NaN
1396,하남시,2022-08,4536.0,13357060.0,15198873.0,NaN,NaN,NaN,NaN,NaN
1395,하남시,2022-09,3531.0,27537465.0,20984856.0,NaN,NaN,NaN,NaN,NaN
1394,하남시,2022-10,4246.0,24568182.0,22506305.0,NaN,NaN,NaN,NaN,NaN
1393,하남시,2022-11,2824.0,15319472.0,18956314.0,NaN,NaN,NaN,NaN,NaN
1392,하남시,2022-12,2286.0,6725929.0,11347566.0,NaN,NaN,NaN,NaN,NaN

In [16]:
population = pd.read_csv("datas/인구'19-'21.csv", encoding='CP949', low_memory=False)

In [28]:
population[population['행정구역별(읍면동)']=='의정부시']

,행정구역별(읍면동),2019,2019.1,2019.2,2019.3,2019.4,2019.5,2019.6,2019.7,2019.8,...,2021.10,2021.11,2021.12,2021.13,2021.14,2021.15,2021.16,2021.17,2021.18,2021.19
116,의정부시,440357,216737,223620,433491,213519,219972,6866,3218,3648,...,185533,129,2300,161749,12320,123866,2955,21553,1055,7430